### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brunocascio**

### CODE REVIEW

**Comment by avdept** [comment]
It will not work if you delete any element from todos.

**Comment by brunocascio** [comment]
Why not? 🤔

**Comment by avdept** [comment]
Assume collection of todos like  `[{id: 0},{id: 1},{id: 2},{id: 3}] `
step1: you delete todo with id===1
todos = [{id: 0},{id: 2},{id: 3}] 
step2: you want to mark todo with id===3 as completed
but todos[3] will be undefined => error

**Comment by brunocascio** [comment]
Hummm, you are finding objects. Sorry.

Just as a comment, you could use the functional approach of ES6 :)

```javascript
this.todos
  .filter((t) => t.id == your_id)
  .map((t) => Object.assign({}, t, {completed: !t.completed}));
```

**Comment by avdept** [comment]
My example was related to this change
https://github.com/ethan-deng/Redux-vs-Alt/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R88

I'm not maintainer, just found this pull request slightly wrong

**Pull request closed without merging**
